name: Packaging
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7
      - name: Verify versions match
        run: |
          POETRY_VERSION=$(poetry version --short)
          TAG_VERSION=$(git describe HEAD --tags --abbrev=0)
          echo "version in pyproject.toml: $POETRY_VERSION"
          echo "git tag: $TAG_VERSION"
          if [[ "$TAG_VERSION" != "v$POETRY_VERSION" ]]; then exit 1; fi
      - name: Build package
        run: poetry build
      - name: Test Publishing
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/simple
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_API_TOKEN }}
          poetry publish --repository test-pypi
      - name: Publish to PyPi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish
